### ISSUE TITLE
Add simple rich list

### ISSUE THREAD

**Issue by streetcrypto7** [cpuchain/web-explorer#1]
Make a simple rich list that can show the list of top 100 addresses with unspent balance

Design)

1. Make a snapshot of unspent balance, run them every 24 hours with cronjob

2. API parses the csv / json file that contains snapshot information

3. API returns 100 addresses with balance on simple GET method

ex) https://api.cpuchain.org/richlist

4. Show the results on explorer like showing blocks.

Or we could just modify the node to make it return the top addresses

**Comment by itwysgsl** [comment]
You may consider implementing something like this https://github.com/hanneskr/smileyCoin/commit/20f71d124b614a25e663e0b745a69a332f91003f

**Comment by streetcrypto7** [comment]
@itwysgsl That is what I was finding for 👍
